master:
  servicePort: 80
  serviceType: LoadBalancer
  InstallPlugins:
  - blueocean:1.22.0
  - credentials-binding:1.16
agent:
  volumes:
  - type: HostPath
    volumeName: docker-sock
    hostPath: /var/run/docker.sock
    mountPath: /var/run/docker.sock
