apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-realworld-example
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rails-realworld-example
  template:
    metadata:
      labels:
        app: rails-realworld-example
    spec:
      containers:
        - name: rails
          image: myartame/rails-realworld-example-app
          resources:
            requests:
              memory: "256M"
              cpu: "200m"
            limits:
              memory: "512M"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 3000
          env:
          - name: DB_HOST
            value: localhost
          - name: DB_USERNAME
            value: sample_user
          - name: DB_PASSWORD
            value: sample_password
          - name: RAILS_ENV
            value: development
          command: ["/bin/bash"]
          args: ["-c", "chmod +x /wait-for-it.sh; /wait-for-it.sh localhost:3306 -t 60; rake db:migrate; rails s -p 3000 -b 0.0.0.0"]
        - name: mysql
          image: mysql:5.7
          resources:
            requests:
              memory: "256M"
              cpu: "200m"
            limits:
              memory: "512M"
              cpu: "500m"
          ports:
            - name: tcp
              containerPort: 3306
          env:
          - name: MYSQL_DATABASE
            value: sample_development
          - name: MYSQL_USER
            value: sample_user
          - name: MYSQL_PASSWORD
            value: sample_password
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "'true'"
