apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rails-realworld-example
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: rails-realworld-example
  targetCPUUtilizationPercentage: 70
